apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2021-04-07T20:33:11Z'
  labels:
    app: simple-webapp-py
  name: simple-webapp-py
  namespace: myproject
  resourceVersion: '5645'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/myproject/buildconfigs/simple-webapp-py
  uid: 7879f3a0-97e0-11eb-8863-08002732e709
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-webapp-py:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/peteranton1/simple-webapp-py.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.6'
        namespace: openshift
    type: Source
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:ac50754646f0d37616515fb30467d8743fb12954260ec36c9ecb5a94499447e0
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 6749e919842d245c
      type: Generic
    - github:
        secret: 4f122c56a54aeef7
      type: GitHub
status:
  lastVersion: 2
